Repository Anth0nyPereira/PI, pull requests merged in 2021-06, with the labels that each got.

#53 Merge/all remaining components
  .gitignore
  m3
  project/.gitignore
  project/.idea/.idea/inspectionProfiles/Project_Default.xml
  project/.idea/.idea/vcs.xml
  project/.idea/.idea/workspace.xml
  project/.idea/misc.xml
  project/.idea/project.iml
  project/app/VGG_.py
  project/app/breed_classifier.py
  project/app/face_recognition.py
  project/app/fileSystemManager.py
  project/app/forms.py
  project/app/models.py
  project/app/nlpFilterSearch.py
  project/app/object_extraction.py
  project/app/processing.py
  project/app/static/css/main.css
  project/app/static/css/mycss.css
  project/app/static/img/chat-right-quote-fill.svg
  project/app/static/img/check2.svg
  project/app/static/img/checked.png
  project/app/static/img/imageable.png
  project/app/static/tests/face.jpg
  project/app/templates/dashboard.html
  project/app/templates/gallery.html
  project/app/templates/index.html
  project/app/templates/landingpage.html
  project/app/templates/objectsGallery.html
  project/app/templates/peopleGallery.html
  project/app/templates/placesGallery.html
  project/app/templates/renaming.html
  project/app/templates/textGallery.html
  project/app/templates/topbar.html
  project/app/utils.py
  project/app/views.py
  project/manage.py
  project/project/urls.py
  project/requirements.txt
  project/running.txt
  project/scripts/esScript.py
  project/scripts/neoScript.py
  project/scripts/pathsPC.py
  project/scripts/pcVariables.py
  project/tests/face.jpg
  project/tests/test_VGG_.py
  project/tests/test_face_recognition.py
  project/tests/test_fileSystemManager.py
  project/tests/test_nlpFilterSearch.py
  project/tests/test_object_extraction.py
  project/tests/test_processing.py
  project/tests/test_utils.py
Labels: enhancement

#56 Feature/filters2
  project/.gitignore
  project/Imageable.py
  project/README.md
  project/app/face_recognition.py
  project/app/fileSystemManager.py
  project/app/models.py
  project/app/nlpFilterSearch.py
  project/app/processing.py
  project/app/static/css/all.css
  project/app/static/css/main.css
  project/app/static/webfonts/fa-brands-400.eot
  project/app/static/webfonts/fa-brands-400.svg
  project/app/static/webfonts/fa-brands-400.ttf
  project/app/static/webfonts/fa-brands-400.woff
  project/app/static/webfonts/fa-brands-400.woff2
  project/app/static/webfonts/fa-regular-400.eot
  project/app/static/webfonts/fa-regular-400.svg
  project/app/static/webfonts/fa-regular-400.ttf
  project/app/static/webfonts/fa-regular-400.woff
  project/app/static/webfonts/fa-regular-400.woff2
  project/app/static/webfonts/fa-solid-900.eot
  project/app/static/webfonts/fa-solid-900.svg
  project/app/static/webfonts/fa-solid-900.ttf
  project/app/static/webfonts/fa-solid-900.woff
  project/app/static/webfonts/fa-solid-900.woff2
  project/app/templates/dashboard.html
  project/app/templates/index.html
  project/app/templates/topbar.html
  project/app/utils.py
  project/app/views.py
  project/project/urls.py
  project/scripts/pathsPC.py
Labels: enhancement

#57 Added some bootstrap files but bootstrap's modal's not working offline
  project/app/static/js/bootstrap.bundle.min.js
  project/app/static/js/bootstrap4-toggle.min.js
  project/app/templates/topbar.html
Labels: enhancement

#58 Merge/all remaining components
  project/.gitignore
  project/Imageable.py
  project/OLDrequirements.txt
  project/README.md
  project/app/face_recognition.py
  project/app/fileSystemManager.py
  project/app/models.py
  project/app/nlpFilterSearch.py
  project/app/processing.py
  project/app/static/css/all.css
  project/app/static/css/main.css
  project/app/static/js/bootstrap.bundle.min.js
  project/app/static/js/bootstrap4-toggle.min.js
  project/app/static/webfonts/fa-brands-400.eot
  project/app/static/webfonts/fa-brands-400.svg
  project/app/static/webfonts/fa-brands-400.ttf
  project/app/static/webfonts/fa-brands-400.woff
  project/app/static/webfonts/fa-brands-400.woff2
  project/app/static/webfonts/fa-regular-400.eot
  project/app/static/webfonts/fa-regular-400.svg
  project/app/static/webfonts/fa-regular-400.ttf
  project/app/static/webfonts/fa-regular-400.woff
  project/app/static/webfonts/fa-regular-400.woff2
  project/app/static/webfonts/fa-solid-900.eot
  project/app/static/webfonts/fa-solid-900.svg
  project/app/static/webfonts/fa-solid-900.ttf
  project/app/static/webfonts/fa-solid-900.woff
  project/app/static/webfonts/fa-solid-900.woff2
  project/app/templates/dashboard.html
  project/app/templates/index.html
  project/app/templates/topbar.html
  project/app/utils.py
  project/app/views.py
  project/project/urls.py
  project/scripts/pathsPC.py
Labels: enhancement

#59 Feature/people tags
  project/app/templates/index.html
  project/app/views.py
  project/scripts/pcVariables.py
Labels: enhancement

#60 Merge/lazy withpeople
  project/.idea/.name
  project/app/face_recognition.py
  project/app/fileSystemManager.py
  project/app/models.py
  project/app/processing.py
  project/app/static/css/bootstrap-grid.css
  project/app/static/css/bootstrap-grid.css.map
  project/app/static/css/bootstrap-grid.min.css
  project/app/static/css/bootstrap-grid.min.css.map
  project/app/static/css/bootstrap-grid.rtl.css
  project/app/static/css/bootstrap-grid.rtl.css.map
  project/app/static/css/bootstrap-grid.rtl.min.css
  project/app/static/css/bootstrap-grid.rtl.min.css.map
  project/app/static/css/bootstrap-reboot.css
  project/app/static/css/bootstrap-reboot.css.map
  project/app/static/css/bootstrap-reboot.min.css
  project/app/static/css/bootstrap-reboot.min.css.map
  project/app/static/css/bootstrap-reboot.rtl.css
  project/app/static/css/bootstrap-reboot.rtl.css.map
  project/app/static/css/bootstrap-reboot.rtl.min.css
  project/app/static/css/bootstrap-reboot.rtl.min.css.map
  project/app/static/css/bootstrap-utilities.css
  project/app/static/css/bootstrap-utilities.css.map
  project/app/static/css/bootstrap-utilities.min.css
  project/app/static/css/bootstrap-utilities.min.css.map
  project/app/static/css/bootstrap-utilities.rtl.css
  project/app/static/css/bootstrap-utilities.rtl.css.map
  project/app/static/css/bootstrap-utilities.rtl.min.css
  project/app/static/css/bootstrap-utilities.rtl.min.css.map
  project/app/static/css/bootstrap.css
  project/app/static/css/bootstrap.css.map
  project/app/static/css/bootstrap.min.css
  project/app/static/css/bootstrap.min.css.map
  project/app/static/css/bootstrap.rtl.css
  project/app/static/css/bootstrap.rtl.css.map
  project/app/static/css/bootstrap.rtl.min.css
  project/app/static/css/bootstrap.rtl.min.css.map
  project/app/static/css/jquery-ui.css
  project/app/static/css/main.css
  project/app/static/js/bootstrap.bundle.js
  project/app/static/js/bootstrap.bundle.js.map
  project/app/static/js/bootstrap.bundle.min.js
  project/app/static/js/bootstrap.bundle.min.js.map
  project/app/static/js/bootstrap.esm.js
  project/app/static/js/bootstrap.esm.js.map
  project/app/static/js/bootstrap.esm.min.js
  project/app/static/js/bootstrap.esm.min.js.map
  project/app/static/js/bootstrap.js
  project/app/static/js/bootstrap.js.map
  project/app/static/js/bootstrap.min.js
  project/app/static/js/bootstrap.min.js.map
  project/app/static/js/bootstrap4-toggle.min.js.map
  project/app/static/js/jquery-ui.js
  project/app/templates/dashboard.html
  project/app/templates/index.html
  project/app/templates/managefolders.html
  project/app/templates/topbar.html
  project/app/views.py
  project/project/urls.py
  project/scripts/pathsPC.py
Labels: enhancement

#63 Feature/website
  project-website/website/css/style.css
  project-website/website/img/imageable.png
  project-website/website/img/installer/1200px-Tux.png
  project-website/website/img/installer/1200px-Windows_logo_-_2012_(dark_blue).png
  project-website/website/index.html
Labels: documentation, enhancement

#64 code cleanup
  project/3.2.2'
  project/Imageable.py
  project/app/VGG_.py
  project/app/face_recognition.py
  project/app/fileSystemManager.py
  project/app/nlpFilterSearch.py
  project/app/processing.py
  project/app/templates/dashboard.html
  project/app/templates/index.html
  project/app/templates/landingpage.html
  project/app/templates/managefolders.html
  project/app/templates/renaming.html
  project/app/templates/topbar.html
  project/app/utils.py
  project/app/views.py
  project/project/urls.py
  project/scripts/pcVariables.py
  project/tests/test_face_recognition.py
  project/tests/test_nlpFilterSearch.py
  project/tests/test_processing.py
  project/tests/test_utils.py
Labels: enhancement

#65 Develop
  project-website/website/css/style.css
  project-website/website/img/imageable.png
  project-website/website/img/installer/1200px-Tux.png
  project-website/website/img/installer/1200px-Windows_logo_-_2012_(dark_blue).png
  project-website/website/index.html
  project/3.2.2'
  project/Imageable.py
  project/app/VGG_.py
  project/app/face_recognition.py
  project/app/fileSystemManager.py
  project/app/nlpFilterSearch.py
  project/app/processing.py
  project/app/templates/dashboard.html
  project/app/templates/index.html
  project/app/templates/landingpage.html
  project/app/templates/managefolders.html
  project/app/templates/renaming.html
  project/app/templates/topbar.html
  project/app/utils.py
  project/app/views.py
  project/project/urls.py
  project/scripts/pcVariables.py
  project/tests/test_face_recognition.py
  project/tests/test_nlpFilterSearch.py
  project/tests/test_processing.py
  project/tests/test_utils.py
Labels: enhancement

#66 Changed link to the linux installer
  project-website/website/index.html
Labels: documentation, enhancement

#72 Readme update and bugfixes
  README.md
  project/OLDrequirements.txt
  project/app/VGG_.py
  project/app/breed_classifier.py
  project/app/nlpFilterSearch.py
  project/app/processing.py
  project/initialize.py
  project/project/settings.py
  project/scripts/pcVariables.py
Labels: enhancement

#73 Develop
  README.md
  project/OLDrequirements.txt
  project/app/VGG_.py
  project/app/breed_classifier.py
  project/app/nlpFilterSearch.py
  project/app/processing.py
  project/initialize.py
  project/project/settings.py
  project/scripts/pcVariables.py
Labels: enhancement

#74 Readme update
  README.md
Labels: documentation

#75 Develop
  README.md
Labels: documentation
